import type { KnipConfig } from "knip";

const config: KnipConfig = {
  workspaces: {
    client: {
      entry: [],
    },
    server: {
      entry: ["server.ts", "db.ts", "routes/**/*.ts", "services/**/*.ts"],
    },
    shared: {
      entry: ["env.ts", "routes.ts"],
    },
  },
  ignore: [
    "**/*.test.{ts,tsx}",
    "tests/**",
    "e2e/**",
    ".lintstagedrc.cjs",
    ".gemini/**",
    ".agent/**",
    "scripts/**",
    "server/lib/cache/redis-client.ts",
    "client/app/components/admin/product-management-unified/shared/hooks/**",
    "client/app/components/admin/shared/**",
    "client/app/components/ui/map/hooks/**",
    "ops/load-testing/**",
    "server/scripts/benchmark-queries.ts",
  ],
  ignoreDependencies: [
    "ts-morph",
    "pino-pretty",
    "@vitejs/plugin-react",
    "protobufjs",
    "@hookform/resolvers",
    "@asteasolutions/zod-to-openapi",
    "@gltf-transform/core",
    "@gltf-transform/extensions",
    "@gltf-transform/functions",
    "@google-cloud/bigquery",
    "@google-cloud/secret-manager",
    "@google-cloud/storage",
    "@google-cloud/tasks",
    "@opentelemetry/auto-instrumentations-node",
    "@opentelemetry/exporter-trace-otlp-http",
    "@opentelemetry/instrumentation-pino",
    "@opentelemetry/resources",
    "@opentelemetry/sdk-node",
    "@opentelemetry/sdk-trace-base",
    "@opentelemetry/semantic-conventions",
    "@react-router/express",
    "compression",
    "express-rate-limit",
    "express-session",
    "express-static-gzip",
    "ffprobe-static",
    "helmet",
    "lru-cache",
    "opossum",
    "passport",
    "passport-google-oauth20",
    "prom-client",
    "sharp",
    "ws",
    "zod",
    "zod-express-middleware",
  ],
  ignoreBinaries: ["tsx", "pkill", "lhci", "wait-on", "react-router", "markdownlint-cli2"],
  ignoreUnresolved: ["./database-metrics-tracker.js"],
  ignoreExportsUsedInFile: true,
};

export default config;
