// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/gallery": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/accessories": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/certifications": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/fabrics": {
    params: {};
  };
  "/fibers": {
    params: {};
  };
  "/manufacturing": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/resources": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/size-charts": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/sustainability": {
    params: {};
  };
  "/technology": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/developer": {
    params: {};
  };
  "/developer/playground": {
    params: {};
  };
  "/developer/guides/:slug": {
    params: {
      "slug": string;
    };
  };
  "/categories": {
    params: {};
  };
  "/categories/:slug": {
    params: {
      "slug": string;
    };
  };
  "/categories/:slug/products": {
    params: {
      "slug": string;
    };
  };
  "/categories/*": {
    params: {
      "*": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/:module/*": {
    params: {
      "module": string;
      "*": string;
    };
  };
  "/api/media": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blog" | "/blog/:slug" | "/gallery" | "/collections" | "/about" | "/accessories" | "/analytics" | "/certifications" | "/contact" | "/dashboard" | "/fabrics" | "/fibers" | "/manufacturing" | "/products" | "/resources" | "/services" | "/size-charts" | "/privacy" | "/sustainability" | "/technology" | "/terms" | "/developer" | "/developer/playground" | "/developer/guides/:slug" | "/categories" | "/categories/:slug" | "/categories/:slug/products" | "/categories/*" | "/admin" | "/admin/:module/*" | "/api/media" | "/*";
  };
  "routes/_public.tsx": {
    id: "routes/_public";
    page: "/" | "/blog" | "/blog/:slug" | "/gallery" | "/collections" | "/about" | "/accessories" | "/analytics" | "/certifications" | "/contact" | "/dashboard" | "/fabrics" | "/fibers" | "/manufacturing" | "/products" | "/resources" | "/services" | "/size-charts" | "/privacy" | "/sustainability" | "/technology" | "/terms" | "/developer" | "/developer/playground" | "/developer/guides/:slug" | "/categories" | "/categories/:slug" | "/categories/:slug/products" | "/categories/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/blog._index.tsx": {
    id: "routes/blog._index";
    page: "/blog";
  };
  "routes/blog.$slug.tsx": {
    id: "routes/blog.$slug";
    page: "/blog/:slug";
  };
  "routes/gallery.tsx": {
    id: "routes/gallery";
    page: "/gallery";
  };
  "routes/collections.tsx": {
    id: "routes/collections";
    page: "/collections";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/accessories.tsx": {
    id: "routes/accessories";
    page: "/accessories";
  };
  "routes/analytics.tsx": {
    id: "routes/analytics";
    page: "/analytics";
  };
  "routes/certifications.tsx": {
    id: "routes/certifications";
    page: "/certifications";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/fabrics.tsx": {
    id: "routes/fabrics";
    page: "/fabrics";
  };
  "routes/fibers.tsx": {
    id: "routes/fibers";
    page: "/fibers";
  };
  "routes/manufacturing.tsx": {
    id: "routes/manufacturing";
    page: "/manufacturing";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/resources.tsx": {
    id: "routes/resources";
    page: "/resources";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/size-charts.tsx": {
    id: "routes/size-charts";
    page: "/size-charts";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/sustainability.tsx": {
    id: "routes/sustainability";
    page: "/sustainability";
  };
  "routes/technology.tsx": {
    id: "routes/technology";
    page: "/technology";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/developer.tsx": {
    id: "routes/developer";
    page: "/developer" | "/developer/playground" | "/developer/guides/:slug";
  };
  "routes/developer._index.tsx": {
    id: "routes/developer._index";
    page: "/developer";
  };
  "routes/developer.playground.tsx": {
    id: "routes/developer.playground";
    page: "/developer/playground";
  };
  "routes/developer.guides.$slug.tsx": {
    id: "routes/developer.guides.$slug";
    page: "/developer/guides/:slug";
  };
  "routes/categories._index.tsx": {
    id: "routes/categories._index";
    page: "/categories";
  };
  "routes/categories.$slug.tsx": {
    id: "routes/categories.$slug";
    page: "/categories/:slug";
  };
  "routes/categories.$slug.products.tsx": {
    id: "routes/categories.$slug.products";
    page: "/categories/:slug/products";
  };
  "routes/categories.$.tsx": {
    id: "routes/categories.$";
    page: "/categories/*";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/:module/*";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/admin.$module.tsx": {
    id: "routes/admin.$module";
    page: "/admin/:module/*";
  };
  "routes/api.media.tsx": {
    id: "routes/api.media";
    page: "/api/media";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_public": typeof import("./app/routes/_public.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/blog._index": typeof import("./app/routes/blog._index.tsx");
  "routes/blog.$slug": typeof import("./app/routes/blog.$slug.tsx");
  "routes/gallery": typeof import("./app/routes/gallery.tsx");
  "routes/collections": typeof import("./app/routes/collections.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/accessories": typeof import("./app/routes/accessories.tsx");
  "routes/analytics": typeof import("./app/routes/analytics.tsx");
  "routes/certifications": typeof import("./app/routes/certifications.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/fabrics": typeof import("./app/routes/fabrics.tsx");
  "routes/fibers": typeof import("./app/routes/fibers.tsx");
  "routes/manufacturing": typeof import("./app/routes/manufacturing.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/resources": typeof import("./app/routes/resources.tsx");
  "routes/services": typeof import("./app/routes/services.tsx");
  "routes/size-charts": typeof import("./app/routes/size-charts.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/sustainability": typeof import("./app/routes/sustainability.tsx");
  "routes/technology": typeof import("./app/routes/technology.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/developer": typeof import("./app/routes/developer.tsx");
  "routes/developer._index": typeof import("./app/routes/developer._index.tsx");
  "routes/developer.playground": typeof import("./app/routes/developer.playground.tsx");
  "routes/developer.guides.$slug": typeof import("./app/routes/developer.guides.$slug.tsx");
  "routes/categories._index": typeof import("./app/routes/categories._index.tsx");
  "routes/categories.$slug": typeof import("./app/routes/categories.$slug.tsx");
  "routes/categories.$slug.products": typeof import("./app/routes/categories.$slug.products.tsx");
  "routes/categories.$": typeof import("./app/routes/categories.$.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/admin.$module": typeof import("./app/routes/admin.$module.tsx");
  "routes/api.media": typeof import("./app/routes/api.media.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};