apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: "Prometheus"
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: "Loki"
      tracesToLogs:
        datasourceUid: "Loki"
        tags: ["requestId"]
        mappedTags: [{ key: "traceId", value: "trace_id" }]
        mapTagNamesEnabled: true
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceId: false
        filterBySpanId: false
      tracesToMetrics:
        datasourceUid: "Prometheus"
        spanAttributes: [{ key: "service.name", value: "service" }]
