apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml

commonLabels:
  app: run-remix
  managed-by: argocd

images:
  - name: gcr.io/PROJECT_ID/run-remix
    newTag: v4.0.3
