import type {
  AboutHero,
  AboutMapLocation,
  AboutSection,
  AboutStatistic,
  AboutTeamMessage,
  AboutTimelineEntry,
  Accessory,
  AnimationError,
  AuditLog,
  Category,
  Certificate,
  ContactPageConfiguration,
  Fabric,
  Fiber,
  Folder,
  FooterConfiguration,
  HomepageHero,
  HomepageProcessCard,
  HomepageSection,
  HomepageSlogan,
  HomepageSustainability,
  Inquiry,
  InsertAboutHero,
  InsertAboutMapLocation,
  InsertAboutSection,
  InsertAboutStatistic,
  InsertAboutTeamMessage,
  InsertAboutTimelineEntry,
  InsertAccessory,
  InsertAnimationError,
  InsertCategory,
  InsertCertificate,
  InsertContactPageConfiguration,
  InsertFabric,
  InsertFiber,
  InsertFolder,
  InsertHomepageHero,
  InsertHomepageProcessCard,
  InsertHomepageSection,
  InsertHomepageSlogan,
  InsertHomepageSustainability,
  InsertInquiry,
  InsertLogoAnimationSettings,
  InsertManufacturingCapability,
  InsertManufacturingHero,
  InsertManufacturingProcess,
  InsertManufacturingQuality,
  InsertMediaAsset,
  InsertNavigationGlassmorphismSettings,
  InsertNavigationItem,
  InsertPerformanceMetric,
  InsertProduct,
  InsertSizeChart,
  InsertStorageAnalysisResult,
  InsertStorageChangeLog,
  InsertSustainabilityGoal,
  InsertSustainabilityHero,
  InsertSustainabilityInitiative,
  InsertSustainabilityMetric,
  InsertTechnologyCta,
  InsertTechnologyEquipment,
  InsertTechnologyGradientSettings,
  InsertTechnologyHero,
  InsertTechnologyInnovation,
  InsertTechnologyResearch,
  InsertTechnologyRoadmap,
  InsertUnifiedSustainability,
  LogoAnimationSettings,
  ManufacturingCapability,
  ManufacturingHero,
  ManufacturingProcess,
  ManufacturingQuality,
  MediaAsset,
  NavigationGlassmorphismSettings,
  NavigationItem,
  PerformanceMetric,
  Product,
  SizeChart,
  StorageAnalysisResult,
  StorageChangeLog,
  SustainabilityGoal,
  SustainabilityHero,
  SustainabilityInitiative,
  SustainabilityMetric,
  TechnologyCta,
  TechnologyEquipment,
  TechnologyGradientSettings,
  TechnologyHero,
  TechnologyInnovation,
  TechnologyResearch,
  TechnologyRoadmap,
  UnifiedSustainability,
  UpsertUser,
  User,
} from "../shared/schema.js";
import type { RepositoryCacheOptions } from "./lib/cache/cache-strategies.js";
import type {
  ProductDetail,
  ProductDetailWithContext,
  ProductSummary,
} from "./lib/db/repositories/product-repository.js";
import { getStorage } from "./lib/storage-singleton.js";
import type {
  IAccessoryRepository,
  ICategoryRepository,
  ICertificateRepository,
  IContactRepository,
  IContentRepository,
  IFabricRepository,
  IFiberRepository,
  IInquiryRepository,
  IManufacturingRepository,
  IMediaRepository,
  INavigationRepository,
  IProductRepository,
  ISizeChartRepository,
  ISustainabilityRepository,
  ISystemRepository,
  ITechnologyRepository,
  IUserRepository,
} from "./repositories/storage-interfaces.js";

export interface IStorage
  extends IUserRepository,
    ICategoryRepository,
    IFiberRepository,
    IFabricRepository,
    ICertificateRepository,
    ISizeChartRepository,
    IAccessoryRepository,
    IMediaRepository,
    IProductRepository,
    INavigationRepository,
    IContactRepository,
    IInquiryRepository,
    IContentRepository,
    ISustainabilityRepository,
    IManufacturingRepository,
    ITechnologyRepository,
    ISystemRepository {}

export const storage = getStorage();
