import fs from "node:fs/promises";
import path from "node:path";

// Helper to read JSON
async function readJson(filePath: string) {
  try {
    const content = await fs.readFile(filePath, "utf-8");
    return JSON.parse(content);
  } catch (_e) {
    return null;
  }
}

async function generateContext() {
  const rootDir = process.cwd();
  const pkg = await readJson(path.join(rootDir, "package.json"));
  const clientPkg = await readJson(path.join(rootDir, "client/package.json"));
  const serverPkg = await readJson(path.join(rootDir, "server/package.json"));
  const dockerfile = await fs.readFile(path.join(rootDir, "Dockerfile"), "utf-8");

  // Extract Node version from Dockerfile
  const nodeVersion = dockerfile.match(/FROM node:(\d+)/)?.[1] || "Unknown";

  const content = `# SYSTEM CONTEXT (Auto-Generated)

**Generated At:** ${new Date().toISOString()}
**Project:** ${pkg.name}
**Version:** ${pkg.version}

## 1. Core Runtime
| Component | Version | Source |
| :--- | :--- | :--- |
| **Node.js** | ${nodeVersion} | Dockerfile |
| **Package Manager** | \`${pkg.packageManager}\` | package.json |
| **Workspace** | TurboRepo ${pkg.devDependencies.turbo} | package.json |

## 2. Stack Versions
### Frontend (@run-remix/client)
| Lib | Version |
| :--- | :--- |
| React | ${clientPkg.dependencies.react} |
| Vite | ${clientPkg.devDependencies.vite} |
| Tailwind | ${clientPkg.dependencies.tailwindcss} |

### Backend (@run-remix/server)
| Lib | Version |
| :--- | :--- |
| Express | ${serverPkg.dependencies.express} |
| Drizzle | ${serverPkg.dependencies["drizzle-orm"]} |
| Neon Driver | ${serverPkg.dependencies["@neondatabase/serverless"]} |

## 3. Scripts
| Command | Definition |
| :--- | :--- |
${Object.entries(pkg.scripts)
  .map(([k, v]) => `| \`npm run ${k}\` | \`${v}\` |`)
  .join("\n")}

---
*Generated by scripts/generate-context.ts. Do not edit manually.*
`;

  await fs.writeFile(path.join(rootDir, "SYSTEM_CONTEXT.md"), content);
}

generateContext().catch(console.error);
