/**
 * RFC 7807 Problem Details for HTTP APIs
 * Standardized error reporting structure.
 */
export interface ProblemDetails {
  /**
   * A URI reference that identifies the problem type.
   * @example "urn:problem:validation-error"
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type.
   * @example "Validation Failed"
   */
  title: string;

  /**
   * The HTTP status code generated by the origin server.
   * @example 400
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   * @example "Email is required."
   */
  detail: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * @example "/api/contact/submission/123"
   */
  instance?: string;

  /**
   * Extension members (e.g., validation issues)
   */
  [key: string]: unknown;
}

// Validation Extension
export interface ValidationProblemDetails extends ProblemDetails {
  type: "urn:problem:validation-error";
  "invalid-params": Array<{
    name: string;
    reason: string;
  }>;
}
